<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (BOOK_TYPE_CODE,SEGMENT9?,DESCRIPTION?,PROYECTO_FA?,ASSET_TYPE,ASSET_NUMBER,FECHA_PUESTA_SERVICIO,SERIAL_NUMBER?,MODEL_NUMBER?,FA_CATEGORY?,DESCRIPTION_1?,PO_NUMBER?,COST,LOCATION_CODE?,LOCATION_DESCRIPTION?,PERIODO_ADICION?)+>
  <!ELEMENT BOOK_TYPE_CODE (#PCDATA)>
  <!ELEMENT SEGMENT9 (#PCDATA)>
  <!ELEMENT DESCRIPTION (#PCDATA)>
  <!ELEMENT PROYECTO_FA (#PCDATA)>
  <!ELEMENT ASSET_TYPE (#PCDATA)>
  <!ELEMENT ASSET_NUMBER (#PCDATA)>
  <!ELEMENT FECHA_PUESTA_SERVICIO (#PCDATA)>
  <!ELEMENT SERIAL_NUMBER (#PCDATA)>
  <!ELEMENT MODEL_NUMBER (#PCDATA)>
  <!ELEMENT FA_CATEGORY (#PCDATA)>
  <!ELEMENT DESCRIPTION_1 (#PCDATA)>
  <!ELEMENT PO_NUMBER (#PCDATA)>
  <!ELEMENT COST (#PCDATA)>
  <!ELEMENT LOCATION_CODE (#PCDATA)>
  <!ELEMENT LOCATION_DESCRIPTION (#PCDATA)>
  <!ELEMENT PERIODO_ADICION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>000000</SEGMENT9>
    <DESCRIPTION>No Aplica</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22419131</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/30 00:00:00</FECHA_PUESTA_SERVICIO>
    <SERIAL_NUMBER>SVTE253810000012</SERIAL_NUMBER>
    <MODEL_NUMBER>FCQ1651X75X</MODEL_NUMBER>
    <FA_CATEGORY>72-1516</FA_CATEGORY>
    <DESCRIPTION_1>SWITCH CISCO WS-C2960C24TT-L</DESCRIPTION_1>
    <COST>2335</COST>
    <LOCATION_CODE>SV-E00-SVMIG-017-1000002-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia San Miguel Centro</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253110</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253109</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253108</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253107</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253106</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253105</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253117</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253116</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253115</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253114</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253113</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253112</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253111</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253104</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA EJECUTIVA INDIA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253103</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA EJECUTIVA INDIA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253102</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA EJECUTIVA INDIA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253101</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TIPO CAJERO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-015-1000008-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>Agencia Servicio T&#63;cnico</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV0000</SEGMENT9>
    <DESCRIPTION>CARGA_INICIAL</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>424986</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2012/09/30 00:00:00</FECHA_PUESTA_SERVICIO>
    <SERIAL_NUMBER>SVTE250210000275</SERIAL_NUMBER>
    <MODEL_NUMBER>PLL3DSH</MODEL_NUMBER>
    <FA_CATEGORY>39-1214</FA_CATEGORY>
    <DESCRIPTION_1>TRANSCEIVER FCLF8521P2BTL-TX</DESCRIPTION_1>
    <COST>173.39</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000019-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA UNICENTRO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>09-12</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV0000</SEGMENT9>
    <DESCRIPTION>CARGA_INICIAL</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>424984</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2012/09/30 00:00:00</FECHA_PUESTA_SERVICIO>
    <SERIAL_NUMBER>SVTE250210000273</SERIAL_NUMBER>
    <MODEL_NUMBER>PLL3D05</MODEL_NUMBER>
    <FA_CATEGORY>39-1214</FA_CATEGORY>
    <DESCRIPTION_1>TRANSCEIVER FCLF8521P2BTL-TX</DESCRIPTION_1>
    <COST>173.39</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000019-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA UNICENTRO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>09-12</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253063</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA EJECUTIVA INDIA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253065</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253066</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA EJECUTIVA INDIA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253067</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253068</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253069</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA EJECUTIVA INDIA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253070</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253071</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253072</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253073</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253074</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253075</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253076</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>BANCO TIPO PACO</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253077</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253078</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253079</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA TRANSPARENTE</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253080</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA BLANCA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253081</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA BLANCA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253082</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA BLANCA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253083</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA EJECUTIVA INDIA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253084</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA BLANCA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>
    <SEGMENT9>SV1160</SEGMENT9>
    <DESCRIPTION>3G New Sites Coverage</DESCRIPTION>
    <PROYECTO_FA>SV9999-99998</PROYECTO_FA>
    <ASSET_TYPE>CAPITALIZED</ASSET_TYPE>
    <ASSET_NUMBER>22253085</ASSET_NUMBER>
    <FECHA_PUESTA_SERVICIO>2013/04/09 00:00:00</FECHA_PUESTA_SERVICIO>
    <FA_CATEGORY>56-1000</FA_CATEGORY>
    <DESCRIPTION_1>SILLA TRIBECA BLANCA</DESCRIPTION_1>
    <COST>0.01</COST>
    <LOCATION_CODE>SV-C00-SVSAL-018-1000021-000</LOCATION_CODE>
    <LOCATION_DESCRIPTION>AGENCIA PLAZA MUNDO</LOCATION_DESCRIPTION>
    <PERIODO_ADICION>04-13</PERIODO_ADICION>
  </DATA_RECORD>
  <DATA_RECORD>
    <BOOK_TYPE_CODE>SV_TELEMOV_IFRS</BOOK_TYPE_CODE>